In [1]:
#Program to perform matrix multiplication

import numpy as np

mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2=np.array([[6,1,2],[4,3,2],[1,3,8]])

print("Matrix mat1 : \n",mat1)
print("\nMatix mat2 : \n",mat2)

m=np.dot(mat1,mat2)

print("\nMultiplication of mat1 and mat2 : \nm = \n",m)

print("\nTranspose of matrix 'm' :\n",np.transpose(m))

Matrix mat1 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matix mat2 : 
 [[6 1 2]
 [4 3 2]
 [1 3 8]]

Multiplication of mat1 and mat2 : 
m = 
 [[ 17  16  30]
 [ 50  37  66]
 [ 83  58 102]]

Transpose of matrix 'm' :
 [[ 17  50  83]
 [ 16  37  58]
 [ 30  66 102]]
